# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  glad_config = debug
  imgui_config = debug
  glm_config = debug
  stb_config = debug
  OpenGLPlayground_config = debug

else ifeq ($(config),release)
  glfw_config = release
  glad_config = release
  imgui_config = release
  glm_config = release
  stb_config = release
  OpenGLPlayground_config = release

else ifeq ($(config),dist)
  glfw_config = dist
  glad_config = dist
  imgui_config = dist
  glm_config = dist
  stb_config = dist
  OpenGLPlayground_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw glad imgui glm stb OpenGLPlayground

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: glad glfw glm imgui stb

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile config=$(glad_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/imgui -f Makefile config=$(imgui_config)
endif

glm:
ifneq (,$(glm_config))
	@echo "==== Building glm ($(glm_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glm -f Makefile config=$(glm_config)
endif

stb:
ifneq (,$(stb_config))
	@echo "==== Building stb ($(stb_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/stb -f Makefile config=$(stb_config)
endif

OpenGLPlayground: glfw glad imgui glm stb
ifneq (,$(OpenGLPlayground_config))
	@echo "==== Building OpenGLPlayground ($(OpenGLPlayground_config)) ===="
	@${MAKE} --no-print-directory -C . -f OpenGLPlayground.make config=$(OpenGLPlayground_config)
endif

clean:
	@${MAKE} --no-print-directory -C Dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/glm -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/stb -f Makefile clean
	@${MAKE} --no-print-directory -C . -f OpenGLPlayground.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   imgui"
	@echo "   glm"
	@echo "   stb"
	@echo "   OpenGLPlayground"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"